local Color, colors, Group, groups, styles = require('colorbuddy').setup()

local M = {}

M.boring = function()
    Color.new('bg', '#000000')
    Color.new('myFg', '#ffffff')
    Color.new('dull', '#c6c6c6')
    Color.new('dark', '#949494')
    Color.new('deep', '#4e4e4e')

    Group.new('Visual', colors.bg, colors.dark, styles.NONE)
    Group.new('Normal', colors.myFg, colors.bg, styles.NONE)
    Group.new('VisualNOS')

    Group.new('PreProc', colors.dull, colors.bg, styles.NONE)
    Group.new('Folded', colors.dark, colors.bg, styles.inverse)
    Group.new('Title', colors.myFg, colors.bg, styles.bold)
    Group.new('Underlined', colors.myFg, colors.bg, styles.underline)
    Group.new('MatchParen', colors.myFg, colors.bg, styles.bold)

    Group.new('SignColumn', colors.bg, colors.myFg, styles.NONE)
    Group.new('ColorColumn', colors.bg, colors.myFg, styles.NONE)
    Group.new('CursorColumn', colors.bg, colors.myFg, styles.NONE)

    Group.new('PMenu', colors.myFg, colors.bg, styles.inverse)
    Group.new('PMenuSel', colors.myFg, colors.bg, styles.bold)
    Group.new('PmenuSbar')
    Group.new('PmenuThumb')

    Group.new('TabLine', colors.myFg, colors.bg, styles.NONE)
    Group.new('TabLineSeparator', colors.myFg, colors.bg, styles.NONE)
    Group.new('TabLineFill', colors.myFg, colors.bg, styles.NONE)
    Group.new('TabLineSel', colors.dark, colors.bg, styles.inverse)
    Group.new('TabLineSelSeparator')

    Group.new('String', colors.dull, colors.bg, styles.italic)
    Group.new('Comment', colors.dark, colors.bg, styles.NONE)
    Group.new('Todo', colors.dark, colors.bg, styles.NONE)
    Group.new('Constant', colors.dull, colors.bg, styles.NONE)
    Group.new('Special', colors.deep, colors.bg, styles.NONE)
    Group.new('SpecialChar')
    Group.new('SpecialComment')
    Group.new('SpecialKey')
    Group.new('Keyword')
    Group.new('Operator')
    Group.new('Number')
    Group.new('Character')
    Group.new('Conditional')
    Group.new('Define')
    Group.new('Boolean')
    Group.new('Delimiter')
    Group.new('Exception')
    Group.new('Float')
    Group.new('Function')
    Group.new('Include')
    Group.new('Identifier')
    Group.new('Structure')
    Group.new('Type')
    Group.new('Typedef')
    Group.new('Statement')

    Group.new('Error')
    Group.new('ErrorMsg')
    Group.new('WarningMsg')
    Group.new('Conceal')
    Group.new('Label')
    Group.new('Repeat')
    Group.new('StorageClass')
    Group.new('Tag')
    Group.new('NonText')
    Group.new('VertSplit')
    Group.new('EndOfBuffer')

    Group.new('SpellBad')
    Group.new('SpellCap')
    Group.new('SpellLocal')
    Group.new('SpellRare')

    Group.new('LineNr')
    Group.new('CursorLineNr')
    Group.new('Line')
    Group.new('StatusLine')
    Group.new('Cursor')
    Group.new('CursorLine')
    Group.new('iCursor')

    Group.new('DiagnosticWarn')
    Group.new('DiagnosticError')
    Group.new('DiagnosticInfo')
    Group.new('DiagnosticHint')
    Group.new('LSPReferenceText')
    Group.new('LSPReferenceRead')
    Group.new('LSPReferenceWrite')
end

return M
