shell={program = "/bin/bash", args = ["--login"] }

import=[
  # "/Users/charlie/.config/alacritty/themes/themes/catppuccin-latte.toml"
  # "/Users/charlie/.config/alacritty/themes/themes/catppuccin-frappe.toml"
  # "/Users/charlie/.config/alacritty/themes/themes/catppuccin-macchiato.toml"
  "/Users/charlie/.config/alacritty/themes/themes/catppuccin-mocha.toml"
]

[env]
TERM="xterm-256color"

[font]
size=23

[font.normal]
family="FiraMono Nerd Font Mono"

[window]
decorations="none"

[window.padding]
x=7
y=0
