shell = { program = "/bin/bash", args = ["--login"] }

import = [
  "/home/charlie/.config/alacritty/themes/themes/tokyonight_night.toml",
]

[font]
size = 18

[font.normal]
family = "IosevkaNerdFontMono"
style = "Regular"

[font.bold]
family = "IosevkaNerdFontMono"
style = "Bold"

[font.italic]
family = "IosevkaNerdFontMono"
style = "Italic"

[window]
decorations = "full"
startup_mode = "maximized"

[window.padding]
x = 7
y = 0
