import=["/Users/charlie/.config/alacritty/themes/themes/tokyo_night.toml"]

[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font Mono", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font Mono", style = "Italic" }
size = 20

[window]
blur = true
decorations = "None"
padding.x = 8
padding.y = 8
opacity = 1
