shell={program = "/bin/bash", args = ["--login"]}

import=["/Users/charlie/.config/alacritty/themes/themes/tokyonight_night.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 20

[font.normal]
family = "ZedMono Nerd Font Mono"
style = "Regular"

[font.bold]
family = "ZedMono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "ZedMono Nerd Font Mono"
style = "Italic"

[window]
decorations = "full"
startup_mode = "maximized"

[window.padding]
x = 7
y = 0
