import=["/Users/charlie/.config/alacritty/themes/themes/gruvbox_dark.toml"]

[font]
size = 25

[font.normal]
family = "ZedMono Nerd Font Mono"
style = "Regular"

[font.bold]
family = "ZedMono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "ZedMono Nerd Font Mono"
style = "Italic"

[window]
decorations = "none"

[window.padding]
x = 7
y = 0
